export const GET_ALL_SAN_PHAM = "GET_ALL_SAN_PHAM";
export const GET_ALL_SAN_PHAM_SAGA = "GET_ALL_SAN_PHAM_SAGA";
export const CREATE_SAN_PHAM = "CREATE_SAN_PHAM";
export const CREATE_SAN_PHAM_SAGA = "CREATE_SAN_PHAM_SAGA";
